//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGamerSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_game
    {
        public string email { get; set; }
        public string nome { get; set; }
        public Nullable<int> classificacao { get; set; }
        public Nullable<int> horas { get; set; }
    
        public virtual game game { get; set; }
        public virtual useraccount useraccount { get; set; }
    }
}
